### ISSUE TITLE
changing the password for current user log in 

### ISSUE THREAD

**Issue by mhhonline** [akveo/ngx-admin-bundle-support#16]
Greetings,

I have bought "ngx-admin Backend Bundle Node + E-comm"

http://localhost:4200/auth/reset-password
reset password:
the error is not returned in the GUI. example. I was putting 12345. the error on the console is “Password should be longer than 6 characters”
on the GUI. .. try later. 
then I tried more than 6 char 
I got :

{"level":"error"}
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
    at invalidArrayBufferView (internal/crypto/cipher.js:87:10)
    at Decipher.update (internal/crypto/cipher.js:148:11)
    at Object.decipherResetPasswordToken (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/src/api/common/auth/cipherHelper.js:48:29)
    at AuthService.resetPassword (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/src/api/common/auth/authService.js:44:33)
    at router.post (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/src/api/common/auth/authController.js:45:6)
    at Layer.handle [as handle_request] (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mohammed-macbookPro/Development/Akveo - E-Commerce/node-ecom/backend/node_modules/express/lib/router/index.js:281:22

Regards,
Mohammed

**Comment by valentinkononov** [comment]
Hi Mohammed! thanks for the issue, will be fixed in the upcoming release. I will close it once done

**Comment by mhhonline** [comment]
thanks

**Comment by popzadid** [comment]
How about this update?
